NETWORK:
  ResNet_CHANNELS: [64, 256, 512, 1024, 2048]
  Convert_CHANNELS: [128, 256, 256, 512, 512]
  UNIFIY_CHANNELS: 66
SOLVER:
  BASE_LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  STEPS: (30000, 45000)
  MAX_ITER: 60000
  MAX_EPOCHES: 100
  CON_THRESH_INIT: 0.7
  CON_THRESH_FINAL: 0.9
  SMALL_LOSS_INIT: 0.0
  SMALL_LOSS_FINAL: 0.4
  NUM_GRADUAL: 20
DATASET:
  SCALE_SIZE: 288
  TARGET_SIZE: 256


